### ISSUE TITLE
.cat domain requests return 'invalid' to idn domain names

### ISSUE THREAD

**Issue by jvmonjo** [domainr/api#1]
.cat registry allows idn domains (accents, ñ, ç, etc..) but responses from the api are returning "invalid" in the summary and in the response.

**Comment by ydnar** [comment]
Which domain(s) produce an `invalid` response? Can you provide an example API query and response JSON (minus your API credentials)?

**Comment by ydnar** [comment]
@jvmonjo it looks like `ñ` is not allowed by the [Catalan registry](http://funcadio.cat/ca/domini):

https://www.iana.org/domains/idn-tables/tables/cat_ca_1.0.html

```
U+002D HYPEN-MINUS
U+0030..U+0039 DIGIT ZERO .. DIGIT 9
U+0061..U+007A LATIN SMALL LETTER A .. LATIN SMALL LETTER Z
U+00B7 MIDDLE DOT
U+00E0 LATIN SMALL LETTER A WITH GRAVE
U+00E7 LATIN SMALL LETTER C WITH CEDILLA
U+00E8 LATIN SMALL LETTER E WITH GRAVE
U+00E9 LATIN SMALL LETTER E WITH ACUTE
U+00ED LATIN SMALL LETTER I WITH ACUTE
U+00EF LATIN SMALL LETTER I WITH DIAERESIS
U+00F2 LATIN SMALL LETTER O WITH GRAVE
U+00F3 LATIN SMALL LETTER O WITH ACUTE
U+00FA LATIN SMALL LETTER U WITH ACUTE
U+00FC LATIN SMALL LETTER U WITH DIAERESIS
```

**Comment by ydnar** [comment]
@jvmonjo thanks for the bug report. You found an edge case with the nic.cat EPP server that our backend didn’t handle. The fix will go out in our next deploy.

**Comment by case** [comment]
@jvmonjo This fix is now live, thanks again for reporting it!

**Comment by jvmonjo** [comment]
I'm still getting false negatives with idn names. Here's an example:
If you query the domain `testç.cat (xn--test-3oa.cat)` you still get invalid. 

```
{
  "status": [
    {
      "domain": "xn--test-3oa.cat",
      "zone": "cat",
      "status": "undelegated inactive invalid",
      "summary": "invalid"
    }
  ]
}
```

But if you check it in the official registry [https://fundacio.cat/ca/domini](https://fundacio.cat/ca/domini) it responds `Available`

**Comment by case** [comment]
@jvmonjo apologies for this, we appreciate your followup — looking deeper, we found a related bug that was causing this. Fix is deployed now.

Let us know if you encounter any other issues like this!

**Comment by jvmonjo** [comment]
It seems that is working fine, now. Thank you ;)
